class AddDataToProperties < ActiveRecord::Migration
  def up
    property = Property.create(:key=>"category", :value=>"painting")
    property = Property.create(:key=>"category", :value=>"drawing/water-color")
    property = Property.create(:key=>"category", :value=>"print/multiple")
    property = Property.create(:key=>"category", :value=>"tapestry")
    property = Property.create(:key=>"category", :value=>"photography")
    property = Property.create(:key=>"medium", :value=>"painting: acrylic")
    property = Property.create(:key=>"medium", :value=>"painting: enamel")
    property = Property.create(:key=>"medium", :value=>"painting: mixed media")
    property = Property.create(:key=>"medium", :value=>"painting: oil")
    property = Property.create(:key=>"medium", :value=>"painting: oil/canvas")
    property = Property.create(:key=>"medium", :value=>"painting: oil/panel")
    property = Property.create(:key=>"medium", :value=>"painting: stained glas")
    property = Property.create(:key=>"medium", :value=>"painting: tempera")
    property = Property.create(:key=>"medium", :value=>"painting: water-paint")
    property = Property.create(:key=>"medium", :value=>"painting: mosaic")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: calligraph")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: chalk")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: charcoal")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: coloured pencils")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: felt pen")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: gouache")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: indian ink")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: lead pencil")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: mixed media/paper")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: pastel")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: pencil")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: red chalk")
    property = Property.create(:key=>"medium", :value=>"drawing/watercolor: watercolour")
    property = Property.create(:key=>"medium", :value=>"print/multiple: aquatint")
    property = Property.create(:key=>"medium", :value=>"print/multiple: copper engraving")
    property = Property.create(:key=>"medium", :value=>"print/multiple: drypoint")
    property = Property.create(:key=>"medium", :value=>"print/multiple: engraving")
    property = Property.create(:key=>"medium", :value=>"print/multiple: etching")
    property = Property.create(:key=>"medium", :value=>"print/multiple: linocut")
    property = Property.create(:key=>"medium", :value=>"print/multiple: lithograph")
    property = Property.create(:key=>"medium", :value=>"print/multiple: offset")
    property = Property.create(:key=>"medium", :value=>"print/multiple: poster")
    property = Property.create(:key=>"medium", :value=>"print/multiple: serigraph")
    property = Property.create(:key=>"medium", :value=>"print/multiple: woodcut")
    property = Property.create(:key=>"medium", :value=>"tapestry: tapestry")
    property = Property.create(:key=>"medium", :value=>"photography: bromoil gelatin silver print")
    property = Property.create(:key=>"medium", :value=>"photography: cprint")
    property = Property.create(:key=>"medium", :value=>"photography: cibachrome print")
    property = Property.create(:key=>"medium", :value=>"photography: daguerreotype")
    property = Property.create(:key=>"medium", :value=>"photography: diapositive")
    property = Property.create(:key=>"medium", :value=>"photography: digital image")
    property = Property.create(:key=>"medium", :value=>"photography: gelatin silver print")
    property = Property.create(:key=>"medium", :value=>"photography: hologram")
    property = Property.create(:key=>"medium", :value=>"photography: polaroid")
    property = Property.create(:key=>"salutation", :value=>"Mr.")
    property = Property.create(:key=>"salutation", :value=>"Mrs.")
    property = Property.create(:key=>"unit", :value=>"cm")
    property = Property.create(:key=>"unit", :value=>"inch")
    property = Property.create(:key=>"purpose", :value=>"for sale")
    property = Property.create(:key=>"purpose", :value=>"for lend")
    property = Property.create(:key=>"purpose", :value=>"for sale or lend")
  end
  def down
    
  end
end